# Generated by Django 5.1.6 on 2025-04-13 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='discriptions',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='discriptions',
            new_name='descriptions',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='created',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='updated',
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ManyToManyField(related_name='get_teacher', to='configapp.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
